FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git gcc g++ cmake sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# miniconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda install -y python=3.7.5 cython numpy

# pytorch
RUN apt-get update && \
    apt-get install -y build-essential libjpeg-dev libpng-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN conda install -y pyyaml scipy ipython mkl mkl-include ninja typing && \
    conda install -y -c pytorch magma-cuda90

WORKDIR /opt/
RUN git clone --recursive -b v1.3.1 --depth 1 https://github.com/pytorch/pytorch.git

WORKDIR /opt/pytorch
RUN git submodule sync && \
    git submodule update --init --recursive
RUN MAX_JOBS=12 \
    TORCH_CUDA_ARCH_LIST="3.7+PTX;5.0;6.0;7.0" \
    TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    pip install -v .
RUN rm -rf /opt/pytorch
